### PR TITLE
V6.2.4

### PR DESCRIPTION
**Pull request by pgarcess**
This change is [Reviewable](https://reviewable.io/reviews/pagamastarde/woocommerce/6)

### CODE REVIEW

**Review by romeritoCL — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pagamastarde/woocommerce/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by romeritoCL — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pagamastarde/woocommerce/6#-:-LON9G726m2-OEZBWYeQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by rmarinleal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pagamastarde/woocommerce/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by rmarinleal — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pagamastarde/woocommerce/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
